title: BRATT's Portfolio
description: "Hacker | Developer | Freelancer - Cybersecurity enthusiast and CTF player. Explore my projects, blog posts, and get in touch!"
url: "https://brattsec.com" # Replace with your actual domain
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

# SEO Settings
author:
  name: "Adhokshaj Kulkarni"
  email: "adhokshajk05@gmail.com"
  description: "Cybersecurity enthusiast and CTF player"
  social:
    github: "adhokshaj-k"
    linkedin: "adhokshaj-kulkarni-22931a1b4"
    twitter: "" # Add if you have one

# SEO Meta Tags
default_meta:
  title: "BRATT's Portfolio - Hacker | Developer | Freelancer"
  description: "Cybersecurity enthusiast and CTF player. Explore my projects, blog posts, and get in touch!"
  keywords: "cybersecurity, CTF, hacking, development, portfolio, freelancer, Adhokshaj Kulkarni"
  author: "Adhokshaj Kulkarni"
  robots: "index, follow"
  og:
    title: "BRATT's Portfolio"
    description: "Cybersecurity enthusiast and CTF player. Explore my projects, blog posts, and get in touch!"
    type: "website"
    image: "/asset/img/og-image.jpg" # Add an Open Graph image
  twitter:
    card: "summary_large_image"
    title: "BRATT's Portfolio"
    description: "Cybersecurity enthusiast and CTF player. Explore my projects, blog posts, and get in touch!"
    image: "/asset/img/twitter-image.jpg" # Add a Twitter card image

# Sitemap Settings
sitemap:
  changefreq: "weekly"
  priority: 0.8

# Build settings
markdown: kramdown
highlighter: rouge

# Process all HTML files as Jekyll templates
include: ["*.html"]

# Make Jekyll process these HTML files
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "*.html"
    values:
      layout: default
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

exclude:
  - .git/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore 